"""Application-wide constants"""

# File Processing
MAX_PREVIEW_ROWS = 100
DEFAULT_CHUNK_SIZE = 10_000
LARGE_FILE_THRESHOLD_MB = 100
MAX_FILE_SIZE_MB = 500

# Database
DEFAULT_DB_TIMEOUT = 30.0
MAX_RETRY_ATTEMPTS = 3
RETRY_DELAY_SECONDS = 0.2
CACHE_TTL_SECONDS = 60

# UI
DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 200
AUTO_REFRESH_INTERVAL_SECONDS = 30

# Storage
DEFAULT_STORAGE_LIMIT_MB = 10240
MIN_FREE_SPACE_MB = 100

# Supported file extensions
SUPPORTED_EXTENSIONS = {".csv", ".xlsx", ".xlsm", ".xltx", ".xltm", ".asc", ".parquet"}

# Model Training
DEFAULT_MAX_EPOCHS = 10
DEFAULT_BATCH_SIZE = 128
DEFAULT_LEARNING_RATE = 0.001

# Statistics
OUTLIER_Z_SCORE_THRESHOLD = 3.0
MISSING_VALUE_ERROR_THRESHOLD = 0.5  # 50%
MISSING_VALUE_WARNING_THRESHOLD = 0.1  # 10%
